id: IC5779C0A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T18:36:39+00:00'
last_modified: '2022-06-08T06:45:31.314866+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22175
  title: གྲུབ་དབང་པདྨ་ལུང་རྟོགས་རྒྱ་མཚོ་མཆོག་གི་རྣམ་ཐར་བྱང་ཆུབ་ལམ་བསྟན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5A51:
      image_group_id: I2784
      title: ''
      total_pages: 124
      order: 1
      base_file: 5A51.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
