id: P006773
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:22:11.713541
source_metadata:
  id: bdr:W22175
  title: གྲུབ་དབང་པདྨ་ལུང་རྟོགས་རྒྱ་མཚོ་མཆོག་གི་རྣམ་ཐར་བྱང་ཆུབ་ལམ་བསྟན
  author: ''
  volumes:
    828e57385bdb485dad9642d2a432b831:
      image_group_id: I2784
      title: ''
      volume_number: 1
      total_pages: 124
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
